name: GTHactions

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5' 

      - name: Run script
        run: python my_script.py

      - name: Commint and Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Actualizacion y Prueba del script
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
